[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:dockerd]
command=/usr/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375
autostart=true
autorestart=true
priority=10
stdout_logfile=/var/log/supervisor/dockerd.log
stderr_logfile=/var/log/supervisor/dockerd-error.log

[program:casaos]
command=/usr/bin/casaos
autostart=true
autorestart=true
priority=20
stdout_logfile=/var/log/supervisor/casaos.log
stderr_logfile=/var/log/supervisor/casaos-error.log
environment=HOME="/root",USER="root"

[program:sshd]
command=/usr/sbin/sshd -D
autostart=true
autorestart=true
priority=30
stdout_logfile=/var/log/supervisor/sshd.log
stderr_logfile=/var/log/supervisor/sshd-error.log
